name: Test Rust code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache rust registery
      uses: Swatinem/rust-cache@v2

    - name: Prepare dependencies
      run: sudo apt-get install coinor-cbc coinor-libcbc-dev

    - name: Check format
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy --tests --examples -- -Dclippy::all

    - name: Build test
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
